# install.packages("pacman")
library(pacman)
p_load(stringr)
p_load(forcats)
p_load(dplyr)
p_load(scales)
p_load(data.table)
p_load(patchwork)
p_load(tidyverse)
p_load(ggthemes)
p_load(ggrepel)
p_load(patchwork)
p_load(matrixStats)
p_load(ggpubr) #drawing, beautifying, ggplot2 compatible
p_load(ggplot2)
p_load(ggforce) #ggplot2 extension
p_load(ggExtra) #ggplot2 extension
p_load(ggthemes) #ggplot2 theme extension
p_load(ggsci)
p_load(RColorBrewer)
p_load(FactoMineR) #PCA Analysis Extension
p_load(factoextra) #PCA Analysis Extension
p_load(scatterplot3d) #Three-dimensional scatter plot
p_load(pheatmap)
p_load(plotly)
p_load(ggplotify)
p_load(cowplot)
p_load(png)
p_load(RUVSeq)
p_load(readxl)
p_load(writexl)
p_load(reshape2)
p_load(ggh4x)
p_load(pvca)
p_load(GGally)
p_load(gg.gap)
p_load(eulerr)
p_load(ComplexUpset)
p_load(IOBR)
p_load(reshape2)
p_load(data.table)
p_load(corrplot)

# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("RUVSeq")